# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
