# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'coursos'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='imagem'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
